CREATE TABLE CUSTOMERS (
    CUSTOMER_ID SERIAL PRIMARY KEY,
    CUSTOMER_CODE VARCHAR(100) UNIQUE NOT NULL,
    CUSTOMER_NAME VARCHAR(255) NOT NULL,
    CUSTOMER_ADDRESS VARCHAR(255),
    CREATE_DATA TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE MEASURE_TYPE (
    MEASURE_TYPE_ID SERIAL PRIMARY KEY,
    MEASURE_TYPE_NAME VARCHAR(50) NOT NULL,
    DESCRIPTION_TYPE TEXT
);

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE MEASURE_DATA (
    MEASURE_UUID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    CUSTOMER_ID INT,
    MEASURE_VALUE DECIMAL(10,2) NOT NULL,
    MEASURE_DATE TIMESTAMP NOT NULL,
    MEASURE_TYPE_ID INT,
    IMAGE_URL VARCHAR(255),
    CREATE_DATA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
    FOREIGN KEY (MEASURE_TYPE_ID) REFERENCES MEASURE_TYPE(MEASURE_TYPE_ID)
);

CREATE TABLE CONFIRMATION(
    CONFIRMATION_ID SERIAL PRIMARY KEY,
    MEASURE_UUID UUID,
    CONFIRMED_VALUE DECIMAL(10,2),
    CONFIRMATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    IS_CONFIRMED BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (MEASURE_UUID) REFERENCES MEASURE_DATA(MEASURE_UUID)
);


INSERT INTO CUSTOMERS (CUSTOMER_CODE, CUSTOMER_NAME ) VALUES('CUSTOMER1', 'Julio');

INSERT INTO MEASURE_TYPE (MEASURE_TYPE_NAME) VALUES ('GAS');
INSERT INTO MEASURE_TYPE (MEASURE_TYPE_NAME) VALUES ('WATER');

INSERT INTO MEASURE_DATA (CUSTOMER_ID,MEASURE_VALUE, MEASURE_DATE, MEASURE_TYPE_ID, IMAGE_URL) VALUES (1, 1250.75, '2024-08-28 14:00:00', 1, 'http://example.com/image1.jpg');

SELECT MD.MEASURE_UUID FROM MEASURE_DATA MD 
INNER JOIN CUSTOMERS C ON C.CUSTOMER_ID = MD.CUSTOMER_ID
INNER JOIN MEASURE_TYPE MT ON MT.MEASURE_TYPE_ID = MD.MEASURE_TYPE_ID
WHERE C.CUSTOMER_CODE = 'Julio' AND
MT.MEASURE_TYPE_NAME = 'GAS' AND
DATE_TRUNC('month', MD.MEASURE_DATE) = DATE_TRUNC('month', '2024-08-28 14:00:00'::timestamp);


psql -U postgres

\l

\c customersMeasure

