version: "3.8"

services:
  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./bd.sql:/docker-entrypoint-initdb.d/bd.sql
    networks:
      - app_network

  node:
    build: .
    container_name: node_app
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_PORT: ${NODE_PORT}
    volumes:
      - ./uploads:/usr/src/app/uploads
      - .:/usr/src/app
    ports:
      - "${NODE_PORT}:80"
    depends_on:
      - db
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
