version: "3.8"

services:
  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: shopper
      POSTGRES_DB: customersMeasure
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./bd.sql:/docker-entrypoint-initdb.d/bd.sql
    networks:
      - app_network

  node:
    build: .
    container_name: node_app
    environment:
      DATABASE_URL: postgres://postgres:shopper@db:5432/customersMeasure
      NODE_PORT: 80
    volumes:
      - ./uploads:/usr/src/app/uploads
      - .:/usr/src/app
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
